package net.regions_unexplored.block.compat;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.FlowerPotBlock;
import net.regions_unexplored.block.RuBlocks;

public class PottedPlants {

    public static void setup() {

        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ALPHA_DANDELION.getId(), RuBlocks.POTTED_ALPHA_DANDELION);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ALPHA_ROSE.getId(), RuBlocks.POTTED_ALPHA_ROSE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ASTER.getId(), RuBlocks.POTTED_ASTER);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLEEDING_HEART.getId(), RuBlocks.POTTED_BLEEDING_HEART);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DAISY.getId(), RuBlocks.POTTED_DAISY);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.FELICIA_DAISY.getId(), RuBlocks.POTTED_FELICIA_DAISY);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DORCEL.getId(), RuBlocks.POTTED_DORCEL);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.FIREWEED.getId(), RuBlocks.POTTED_FIREWEED);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GLISTERING_BLOOM.getId(), RuBlocks.POTTED_GLISTERING_BLOOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.HIBISCUS.getId(), RuBlocks.POTTED_HIBISCUS);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.HYSSOP.getId(), RuBlocks.POTTED_HYSSOP);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MALLOW.getId(), RuBlocks.POTTED_MALLOW);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.POPPY_BUSH.getId(), RuBlocks.POTTED_POPPY_BUSH);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.SALMON_POPPY_BUSH.getId(), RuBlocks.POTTED_SALMON_POPPY_BUSH);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TSUBAKI.getId(), RuBlocks.POTTED_TSUBAKI);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WARATAH.getId(), RuBlocks.POTTED_WARATAH);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WHITE_TRILLIUM.getId(), RuBlocks.POTTED_WHITE_TRILLIUM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WILTING_TRILLIUM.getId(), RuBlocks.POTTED_WILTING_TRILLIUM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLUE_LUPINE.getId(), RuBlocks.POTTED_BLUE_LUPINE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PINK_LUPINE.getId(), RuBlocks.POTTED_PINK_LUPINE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PURPLE_LUPINE.getId(), RuBlocks.POTTED_PURPLE_LUPINE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.RED_LUPINE.getId(), RuBlocks.POTTED_RED_LUPINE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.YELLOW_LUPINE.getId(), RuBlocks.POTTED_YELLOW_LUPINE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ORANGE_CONEFLOWER.getId(), RuBlocks.POTTED_ORANGE_CONEFLOWER);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PURPLE_CONEFLOWER.getId(), RuBlocks.POTTED_PURPLE_CONEFLOWER);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WHITE_SNOWBELLE.getId(), RuBlocks.POTTED_WHITE_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.LIGHT_GRAY_SNOWBELLE.getId(), RuBlocks.POTTED_LIGHT_GRAY_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GRAY_SNOWBELLE.getId(), RuBlocks.POTTED_GRAY_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.RED_SNOWBELLE.getId(), RuBlocks.POTTED_RED_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ORANGE_SNOWBELLE.getId(), RuBlocks.POTTED_ORANGE_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.YELLOW_SNOWBELLE.getId(), RuBlocks.POTTED_YELLOW_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.LIME_SNOWBELLE.getId(), RuBlocks.POTTED_LIME_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GREEN_SNOWBELLE.getId(), RuBlocks.POTTED_GREEN_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.CYAN_SNOWBELLE.getId(), RuBlocks.POTTED_CYAN_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.LIGHT_BLUE_SNOWBELLE.getId(), RuBlocks.POTTED_LIGHT_BLUE_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLUE_SNOWBELLE.getId(), RuBlocks.POTTED_BLUE_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PURPLE_SNOWBELLE.getId(), RuBlocks.POTTED_PURPLE_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MAGENTA_SNOWBELLE.getId(), RuBlocks.POTTED_MAGENTA_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PINK_SNOWBELLE.getId(), RuBlocks.POTTED_PINK_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BROWN_SNOWBELLE.getId(), RuBlocks.POTTED_BROWN_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLACK_SNOWBELLE.getId(), RuBlocks.POTTED_BLACK_SNOWBELLE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DAY_LILY.getId(), RuBlocks.POTTED_DAY_LILY);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MEADOW_SAGE.getId(), RuBlocks.POTTED_MEADOW_SAGE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.CAVE_HYSSOP.getId(), RuBlocks.POTTED_CAVE_HYSSOP);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BARREL_CACTUS.getId(), RuBlocks.POTTED_BARREL_CACTUS);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DUSKTRAP.getId(), RuBlocks.POTTED_DUSKTRAP);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.CORPSE_FLOWER.getId(), RuBlocks.POTTED_CORPSE_FLOWER);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.COBALT_EARLIGHT.getId(), RuBlocks.POTTED_COBALT_EARLIGHT);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TALL_COBALT_EARLIGHT.getId(), RuBlocks.POTTED_TALL_COBALT_EARLIGHT);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MYCOTOXIC_DAISY.getId(), RuBlocks.POTTED_MYCOTOXIC_DAISY);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GLISTER_SPIRE.getId(), RuBlocks.POTTED_GLISTER_SPIRE);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLUE_BIOSHROOM.getId(), RuBlocks.POTTED_BLUE_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GREEN_BIOSHROOM.getId(), RuBlocks.POTTED_GREEN_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PINK_BIOSHROOM.getId(), RuBlocks.POTTED_PINK_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.YELLOW_BIOSHROOM.getId(), RuBlocks.POTTED_YELLOW_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TALL_BLUE_BIOSHROOM.getId(), RuBlocks.POTTED_TALL_BLUE_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TALL_GREEN_BIOSHROOM.getId(), RuBlocks.POTTED_TALL_GREEN_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TALL_PINK_BIOSHROOM.getId(), RuBlocks.POTTED_TALL_PINK_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.TALL_YELLOW_BIOSHROOM.getId(), RuBlocks.POTTED_TALL_YELLOW_BIOSHROOM);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ASHEN_SAPLING.getId(), RuBlocks.POTTED_ASHEN_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ALPHA_SAPLING.getId(), RuBlocks.POTTED_ALPHA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.APPLE_OAK_SAPLING.getId(), RuBlocks.POTTED_APPLE_OAK_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BAMBOO_SAPLING.getId(), RuBlocks.POTTED_BAMBOO_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BAOBAB_SAPLING.getId(), RuBlocks.POTTED_BAOBAB_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLACKWOOD_SAPLING.getId(), RuBlocks.POTTED_BLACKWOOD_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BRIMWOOD_SAPLING.getId(), RuBlocks.POTTED_BRIMWOOD_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.COBALT_SAPLING.getId(), RuBlocks.POTTED_COBALT_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.CACTUS_FLOWER.getId(), RuBlocks.POTTED_CACTUS_FLOWER);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MAGNOLIA_SAPLING.getId(), RuBlocks.POTTED_MAGNOLIA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.CYPRESS_SAPLING.getId(), RuBlocks.POTTED_CYPRESS_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DEAD_PINE_SAPLING.getId(), RuBlocks.POTTED_DEAD_PINE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.DEAD_SAPLING.getId(), RuBlocks.POTTED_DEAD_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.EUCALYPTUS_SAPLING.getId(), RuBlocks.POTTED_EUCALYPTUS_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.FLOWERING_SAPLING.getId(), RuBlocks.POTTED_FLOWERING_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.GOLDEN_LARCH_SAPLING.getId(), RuBlocks.POTTED_GOLDEN_LARCH_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.JOSHUA_SAPLING.getId(), RuBlocks.POTTED_JOSHUA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.KAPOK_SAPLING.getId(), RuBlocks.POTTED_KAPOK_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.LARCH_SAPLING.getId(), RuBlocks.POTTED_LARCH_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MAPLE_SAPLING.getId(), RuBlocks.POTTED_MAPLE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.MAUVE_SAPLING.getId(), RuBlocks.POTTED_MAUVE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ORANGE_MAPLE_SAPLING.getId(), RuBlocks.POTTED_ORANGE_MAPLE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PALM_SAPLING.getId(), RuBlocks.POTTED_PALM_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PINE_SAPLING.getId(), RuBlocks.POTTED_PINE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.BLUE_MAGNOLIA_SAPLING.getId(), RuBlocks.POTTED_BLUE_MAGNOLIA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.PINK_MAGNOLIA_SAPLING.getId(), RuBlocks.POTTED_PINK_MAGNOLIA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.REDWOOD_SAPLING.getId(), RuBlocks.POTTED_REDWOOD_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.RED_MAPLE_SAPLING.getId(), RuBlocks.POTTED_RED_MAPLE_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.ENCHANTED_BIRCH_SAPLING.getId(), RuBlocks.POTTED_ENCHANTED_BIRCH_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.SILVER_BIRCH_SAPLING.getId(), RuBlocks.POTTED_SILVER_BIRCH_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.SMALL_OAK_SAPLING.getId(), RuBlocks.POTTED_SMALL_OAK_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.SOCOTRA_SAPLING.getId(), RuBlocks.POTTED_SOCOTRA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WHITE_MAGNOLIA_SAPLING.getId(), RuBlocks.POTTED_WHITE_MAGNOLIA_SAPLING);
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(RuBlocks.WILLOW_SAPLING.getId(), RuBlocks.POTTED_WILLOW_SAPLING);
    }
}
